### ISSUE TITLE
Genérico para cualquier CKAN y cualquier dataset CSV.

### ISSUE THREAD

**Issue by martinszy** [franciclo/burbujas-de-torta#1]
¿Qué pasa si hacemos que consuma la API de CKAN, obtenga un listado de datasets y permita seleccionar el dataset?
El campo con la url del CKAN debería ser editable, para poder trabajar con cualquier CKAN.
Obviamente sólo filtrar los CSV.

Ejemplo: http://datos.gob.ar/api/3/action/resource_search?query=format:CSV

Lo que habría que hacer para implementar esto:
Agregar un input text en el html, con un valor por defecto que sea "http://datos.gob.ar" y un label que sea "URL del CKAN" o algo así.
Luego en el JS tomar el valor de ese input, agregarle "/api/3/action/resource_search?query=format:CSV" y hacer un d3.json con esa url.
Una vez que vuelve ese request, se agrega un select en la página, con el listado de todos los datasets en CSV del ckan, para esto se itera por los valores que devolvió el json, sería data.result.results y ahí de cada item el item.description sería el texto de cada nuevo <option> que agregamos al select y el item.url sería el value.
Finalmente tomamos el value de la primera opción del select y ahí llamamos al d3.csv que está actualmente en la línea 18.
Además habría que poner un botón para actualizar el ckan cuando se cambia la URL del input.
Y monitorear el evento onchange del select para volver a ejecutar todo con otro dataset.

**Comment by franciclo** [comment]
Joya, hay que ver como se haría ese cross-origin request, desde d3.js
Estoy leyendo esto:
https://github.com/mbostock/d3/wiki/Requests

**Comment by martinszy** [comment]
Si la API está bien configurada no deberías tener ningún obstáculo, lo maneja todo el navegador.

**Comment by franciclo** [comment]
Probaste usar una url? 
Yo intente y me tira el error de cross origin

XMLHttpRequest cannot load http://datos.gob.ar/dataset/89f1a2dd-ad79-4211-87b4-44661d81ac0d/resource/84e23782-7d52-4724-a4ba-2f9621fa5f4e/download/presupuesto-2016.csv. No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by franciclo** [comment]
Probe una url que devuelve un .csv, pero tiene seteado el header Access-Control-Allow-Origin = *
y lo puedo usar sin problemas.

mientras que la url de datos.gob no tiene ese header por eso tira el error creo yo.

Dataset datos.gob:

> Status: HTTP/1.0 200 OK
> Server:    PasteWSGIServer/0.5 Python/2.7.5  
> Date:  Tue, 22 Mar 2016 17:29:55 GMT  
> Pragma:    no-cache  
> Cache-Control: no-cache  
> Accept-Ranges: bytes  
> Last-Modified: Fri, 18 Mar 2016 18:25:54 GMT  
> Content-Range: bytes 0-4819749/4819750 
> ETag:  "1458325554.74-4819750" 
> Content-Type:  text/csv (BOM UTF-8)

Otra url cross origin:
(https://raw.githubusercontent.com/plotly/datasets/master/2014_apple_stock.csv)

> Status: HTTP/1.1 200 OK
> Content-Security-Policy:   default-src 'none'; style-src 'unsafe-inline'  
> X-XSS-Protection:  1; mode=block  
> X-Frame-Options:   deny  
> X-Content-Type-Options:    nosniff 
> Strict-Transport-Security: max-age=31536000  
> ETag:  "f56267228f85d71741e5513e0b86756d83a89270"  
> Content-Type:  text/plain; charset=utf-8  
> Cache-Control: max-age=300 
> X-GitHub-Request-Id:   B91F1126:38F1:39AD7FA:56F18088  
> Content-Encoding:  gzip  
> Content-Length:    2048  
> Accept-Ranges: bytes  
> Date:  Tue, 22 Mar 2016 17:27:40 GMT  
> Via:   1.1 varnish 
> Connection:    close  
> X-Served-By:   cache-fra1228-FRA  
> X-Cache:   MISS  
> X-Cache-Hits:  0  
> Vary:  Authorization,Accept-Encoding  
> Access-Control-Allow-Origin:   \*  
> X-Fastly-Request-ID:   33a7e4c64f28df4de9536f9c26094141750e153a  
> Expires:   Tue, 22 Mar 2016 17:32:40 GMT  
> Source-Age:    0

**Comment by martinszy** [comment]
Levantale un issue a @carohadad

**Comment by franciclo** [comment]
http://docs.ckan.org/en/latest/maintaining/configuration.html#cors-settings
Se puede desde CKAN agregar este header.

**Comment by franciclo** [comment]
Podría levantar un issue, pero esto seria para poder visualizar los datasets disponibles de datos.gob, el tema que estaríamos dejando de lado la idea original de trabajar con cualquier CKAN.

**Comment by franciclo** [comment]
Ariel tiro la posta:
https://crossorigin.me/

**Comment by martinszy** [comment]
No che, creo que no sería problema del framework sino de la implementación en el servidor. Igual con esa que te tiró Ariel pasa a ser re posible todo.

**Comment by franciclo** [comment]
Hecho!
